# This is a basic workflow to help you get started with Actions

name: Azure Government
on:
  # Only run manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Change AZ CLI to connect to Azure Government
    - name: Set AzCLI Gov
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az cloud set --name AzureUSGovernment

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZGOVSP}}
        enable-AzPSSession: true
        
    - name: Create Resource Group
      run: |
        az group create --name anftest-env --location usgovvirginia

    - name: Deploy Template
      run: |
        az deployment group create \
          --resource-group anftest-env \
          --template-file ./anf-test-net.azrm.json \
          --parameters vmAdminPassword=${{secrets.AZVMPASS}}
        

